server:
  port: 8051



spring:
  mqtt:
    username:
    password:
    url: tcp://192.168.11.101:1883
    topics: test/java
    completionTimeout: 3000
    client:
      id: client_c23li34e32s2324
    default:
      qos: 2